route:
  - match:
      severity: test-telegram
    receiver: stardata-telegram
receivers:
- name: 'stardata-telegram'
  telegram_configs:
  - bot_token: '6244055820:AAG_5YYbuy6hSPRt3uKJdFkcED6ZvrejkPY'
    api_url: https://api.telegram.org
    chat_id: '-1001908199366' 
    parse_mode: ''

