version: '3'
services:
    prometheus:
        image: ubuntu/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/:/etc/prometheus/

    grafana:
        image: grafana/grafana-enterprise:latest
        ports:
            - "3000:3000"
