global:
  evaluation_interval: 15s
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['172.17.0.1:9093']

rule_files:
  - 'alerts.yml'
scrape_configs:
- job_name: node
  static_configs:
  - targets:
    - 192.168.10.3:9100
    - 192.168.10.2:9100
