groups:
  - name: dbaas
    rules:
    - alert: DBaaS down
      expr: up = 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "DBaaS down in {{ $labels.instance }}"
        description: "DBaas cluster {{ $labels.ds_id }} is down. Please check your cluster or write a ticket to the support team."

    - alert: High CPU usage 
      expr: dbaas_cpu > 90
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High CPU usage on DB instance {{ $labels.ds_id }}"
        description: "The CPU usage on the DB instance {{ $labels.ds_id }} has been above 90% for more than 5 minutes.\n Current value: {{ $value }}"

    - alert: High memory usage 
      expr: dbaas_memory_percent > 90
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High memory usage on DB instance {{ $labels.ds_id }}"
        description: "The memory usage on the DB instance {{ $labels.ds_id }} has been above 90% for more than 5 minutes.\n Current value: {{ $value }}"

    - alert: Disk space usage is High
      expr: dbaas_disk_percent >= 80
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "Disk space usage on DB instance {{ $labels.ds_id }}"
        description: "The disk space usage on the DB instance {{ $labels.ds_id }} reached high level.\n Current value: {{ $value }}. Please check your cluster configuration."


