groups:
- name: example
  rules:
  - alert: TargetDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Machine is down"
      description: "The target machine is not responding. Investigate immediately."

