groups:
- name: dbaas
  rules:

  - alert: DBaaSDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "DBaaS cluster down on {{ $labels.instance }}"
      description: "The DBaaS cluster {{ $labels.ds_id }} on host {{ $labels.instance }} is down. Investigate and take necessary actions."

  - alert: HighCPUUsage
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node", mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: |
        The CPU usage on the host {{ $labels.instance }} has been above 90% for more than 5 minutes.
        Current value: {{ $value }}%.

  - alert: HighMemoryUsage
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: |
        The memory usage on the host {{ $labels.instance }} has been above 90% for more than 5 minutes.
        Current value: {{ $value }}%.

  - alert: DiskSpaceHighUsage
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: "High disk space usage on {{ $labels.instance }}"
      description: |
        The disk space usage on the host {{ $labels.instance }} has reached a critical level.
        Current value: {{ $value }}%. Please check your storage configuration.

